trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  slnPath: BakeryShop.WebApp
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: dotnet sdk 5
  inputs:
    packageType: 'sdk'
    version: '5.x'

- task: UseDotNet@2
  displayName: dotnet runtime 3.1
  inputs:
    packageType: 'runtime'
    version: '3.1.x'
- script: dotnet build --configuration Release
  displayName: dotnet build
  workingDirectory: $(slnPath)
- script: dotnet test
    --configuration Release
    --collect:"XPlat Code Coverage"
    --results-directory $(Agent.TempDirectory)
    --DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
  displayName: dotnet test
  workingDirectory: $(slnPath)
- script: dotnet publish
    --configuration Release
    --output $(Build.ArtifactStagingDirectory)
  displayName: dotnet publish
  workingDirectory: $(slnPath)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(f6e522a4-e0c2-446e-bb78-f84383da2803)'
    appType: 'webApp'
    WebAppName: 'revature-ashlienguyen'
    packageForLinux: '$(Build.ArtifactStagingDirectory)'